---
abstract: 'PerlIO layer for gzip (de)compression'
author:
  - unknown
build_requires:
  Module::Build: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PerlIO-via-gzip
provides:
  PerlIO::via::gzip:
    file: lib/PerlIO/via/gzip.pm
    version: '0.03'
requires:
  IO::Compress::Gzip: '2'
  IO::Uncompress::Gunzip: '2'
resources:
  bugtracker: https://github.com/majensen/perlio-via-gzip/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/majensen/perlio-via-gzip.git
version: '0.03'
x_perl: '5.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
